### ISSUE TITLE
Branch Casos - Before Merging

### ISSUE THREAD

**Issue by MGeovany** [MGeovany/cei-web-portal#25]
- Las tarjetas de casos de exito no muestran el sombreado exterior, revisar esto antes de enviar Pull Request
 
![image](https://user-images.githubusercontent.com/37640685/180667538-554ce62c-db7c-44d3-a9c1-97f1826ced5d.png)

- Editar el margen entre tarjeta para que en la vista se vean 4 tarjetas y no 3

![image](https://user-images.githubusercontent.com/37640685/180667580-68f021a0-3f79-4fef-b961-6493f8991dbc.png)

- Texto de las tarjetas esta centrado, debe ser alineado a la izquierda.

![image](https://user-images.githubusercontent.com/37640685/180667662-29271eae-17ac-49b9-8f04-1924f1b1d9f9.png)

- Espacio entre `Tecnologia` y las tarjetas debe de ser menos

![image](https://user-images.githubusercontent.com/37640685/180667676-387bed5b-f2c3-4bf7-b9cb-eb361d95943c.png)

- Por favor cambiar que el modal solamente se abra cuando se le de click al texto `Leer Mas` y no a la tarjeta
 
![image](https://user-images.githubusercontent.com/37640685/180667712-48d4c8c1-3a63-4519-a3ad-cea97b0f472f.png)

**Comment by wpayze** [comment]
También podes dejar el texto centrado y centrar el titulo también :)
